#### Import Necessaary Libraries

In [17]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

#### Import Dataset

In [3]:
Cars_data =pd.read_csv("Cars.csv")
Cars_data

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

#### Data Understanding

In [7]:
Cars_data.shape
Cars_data.isna().sum()
Cars_data.dtypes
Cars_data.describe()

               HP        MPG         VOL          SP         WT
count   81.000000  81.000000   81.000000   81.000000  81.000000
mean   117.469136  34.422076   98.765432  121.540272  32.412577
std     57.113502   9.131445   22.301497   14.181432   7.492813
min     49.000000  12.101263   50.000000   99.564907  15.712859
25%     84.000000  27.856252   89.000000  113.829145  29.591768
50%    100.000000  35.152727  101.000000  118.208698  32.734518
75%    140.000000  39.531633  113.000000  126.404312  37.392524
max    322.000000  53.700681  160.000000  169.598513  52.997752

#### Data Preparation

In [9]:
X = Cars_data[["HP","VOL","SP","WT"]]
y = Cars_data["MPG"]

#### Model Building

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=32,shuffle=True)

In [12]:
model = LinearRegression()

#### Model Training

In [13]:
model.fit(X_train,y_train)

LinearRegression()

#### Model Testing

In [14]:
y_pred = model.predict(X_test)
y_pred

array([37.10328425, 32.6395501 , 47.82782017, 40.39141028, 36.07571914,
       34.45595991, 48.33648626, 41.34640714, 35.07429786, 38.25731081,
       29.9401738 , 32.5083074 , 35.05075736, 40.91108486, 39.06368747,
       28.96152853, 37.15217434])

#### Model Evaluation

In [19]:
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MSE: 29.23820115624443
R2 Score: 0.5770101929490707